### ISSUE TITLE
Calling Formula.sha1 is disabled!

### ISSUE THREAD

**Issue by mbocek** [jenv/homebrew-jenv#2]
I have a problem during calling upgrade:
```
Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/jenv/homebrew-jenv/jenv.rb:6:in `<class:Jenv>'
Please report this to the jenv/jenv tap!
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/utils.rb:86:in `odeprecated'
/usr/local/Homebrew/Library/Homebrew/utils.rb:94:in `odisabled'
/usr/local/Homebrew/Library/Homebrew/compat/sha1.rb:3:in `sha1'
/usr/local/Homebrew/Library/Taps/jenv/homebrew-jenv/jenv.rb:6:in `<class:Jenv>'
/usr/local/Homebrew/Library/Taps/jenv/homebrew-jenv/jenv.rb:3:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:201:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:241:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:272:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:255:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1364:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1362:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1362:in `installed'
/usr/local/Homebrew/Library/Homebrew/keg.rb:342:in `installed_dependents'
/usr/local/Homebrew/Library/Homebrew/keg.rb:95:in `block in find_some_installed_dependents'
/usr/local/Homebrew/Library/Homebrew/keg.rb:94:in `each'
/usr/local/Homebrew/Library/Homebrew/keg.rb:94:in `find_some_installed_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:87:in `check_for_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:83:in `handle_unsatisfied_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:31:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

**Comment by gcuisinier** [comment]
Hello,

The jenv tap is no more used.
jenv is now in the official homebrew repo

**Comment by mbocek** [comment]
OK, thanks.
